web-push-libs/pywebpush

pywebpush/__init__.py
Removed duplicate description for :param reg_id: in WebPusher.send method docstring.
=> Updating docstring for WebPusher.send method

pywebpush/__init__.py, pywebpush/tests/test_webpush.py
FCM, unfortunately, rejects multiple parameter sets for Crypto-Key.
This is a work-around fix until the issue is properly resolved by the
respective working groups.
closes #8
=> bug: append vapid and encryption headers with a ';'

pywebpush/__init__.py
Hi, there!
Great library, really simple to use.
I'm trying to use it with new Python 3.5 asyncio network library and it's proving tedious to have to copy-paste the whole ```send``` method in order to change just the last line, where the method calls ```requests.post```. This pull request changes ```requests.post``` call into call to ```self._post```, which makes it easy to subclass and override method ```_post``` and use another networking library if one wishes, keeping the business logic the same.
There are no backwards incompatible changes. The default is still requests, test coverage is still at 100%. I tested the library on Python 2.7, PyPy and Python 3.5.
=> Facilitate easier use of another networking library

pywebpush/__init__.py
GCM doesn't support TTL header, only `time_to_live` parameter and default value is 4 weeks instead zero, so this line also ensures consistency.
=> GCM ttl fix

MANIFEST.in, README.md, README.rst, convert_readme.sh, pywebpush/__init__.py, pywebpush/__main__.py, pywebpush/tests/test_webpush.py, requirements.txt, setup.py, test-requirements.txt
* added primative CLI
* dump as curl
closes #44
=> feat: Allow VAPID with [gf]cm

README.md, README.rst, pywebpush/__init__.py, pywebpush/tests/test_webpush.py, requirements.txt, setup.py, test-requirements.txt
* uses lastest ece(1.7.2) and vapid libraries (1.2.1)
* Will attempt to autofill vapid `aud` from the endpoint if VAPID
requested
* Allows for the older `'aesgcm'` and newer, albeit not as widely
supported `'aes128gcm'` encryption content types.
* Includes fixes provided by https://github.com/Flimm
closes: #49, #48, #42
Includes: #50, #51, #52
=> feat: update to use Cryptography library

README.md, README.rst, convert_readme.sh
It looks like the newly uploaded package on PyPI still doesn't render the RST correctly!
https://pypi.python.org/pypi/pywebpush
This should hopefully fix it for good this time. As a bonus, it makes README.md look prettier on GitHub, and it includes a command that checks for errors within `convert_readme.sh`.
=> Fix RST again

pywebpush/__init__.py
The "Content-Length" transmitted with the curl request should be the length of the encoded data, not the length of the "--data-binary ..." command line parameter.
=> as_curl() content-length typo fix

.travis.yml
Hi,
I am using this package on python 3.4. It works fine. So just to be sure that nothing break if somebody makes any change, I think it would be useful. Moreover it does no harm to add this :)
Thanks
=> add python 3.4 and 3.5 to travis

README.md, pywebpush/__init__.py, pywebpush/tests/test_webpush.py
Hi,
This pull request allows users to set the requests timeout parameter when sending a push. I think it is important for all production code to prevent lock to happen.
If you are ok to merge this, could you make a minor release quickly on pypi ?
Thanks
=> add requests timeout parameter

pywebpush/__init__.py
Use `Vapid.from_string()` instead of `Vapid.from_der()`, which accepts both PEM and DER bytes.
=> webpush(): allow PEM format private key string

pywebpush/__init__.py, pywebpush/tests/test_webpush.py
If the caller of `webpush()` already has a `py_vapid.Vapid` instance lying around, allow passing it as the `vapid_private_key` argument instead of forcing the developer to go back to the private key string just to regenerate a Vapid instance.
=> webpush(): Allow passing Vapid instance 

pywebpush/__init__.py, requirements.txt
remove crypto upper version limit
bump py-vapid base version
=> bug: update to use vapid 'from_string' function

pywebpush/__init__.py, pywebpush/tests/test_webpush.py
Altering subscriptions reference by changing the keys from string to
byte causes hard to debug issues in libraries. For exemple, trying to
call `json.dumps()` after initializing `WebPusher` throws an error
because json cannot handle bytes.
=> Copy subscription before altering the keys.

README.rst, pywebpush/__init__.py, pywebpush/tests/test_webpush.py, setup.py
=> bug: Update vapid `exp` value if it's expired.

pywebpush/__init__.py
In Python 2, using six.string_types causes the code to attempt to re-encode already encoded data because six.string_types matches Python 2 str and unicode data.  Using six.text_type makes sure that the code only attempts to encode unicode data.
=> Use six.text_type instead of six.string_types

CHANGELOG.md, requirements.txt, setup.py
=> bug: update minimum vapid requirement to 1.7.0

pywebpush/__init__.py, pywebpush/__main__.py, pywebpush/tests/test_webpush.py
Add support for adding extra headers when using the `webpush()` function.
It'd be nicer to add the `headers` kwarg in a similar position in the argument list to where it is in `.send()`, but added it to the bottom of the list to avoid changing argument order for those using positional arguments.
I haven't added explicit kwargs for `Urgency` and `Topic` to keep this PR small, but it'd be nice to add them to match the `TTL` support.
Implements https://github.com/web-push-libs/pywebpush/issues/120
=> Webpush headers

requirements.txt
After a fresh install
```
$ python3 -m venv venv
$ . venv/bin/activate
$ pip3 install pywebpush
```
pywebpush fails with a missing dependency:
```
$ python3 -c "import pywebpush"
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pywebpush/pywebpush/__init__.py", line 16, in <module>
import six
ModuleNotFoundError: No module named 'six'
```
six was never listed in `requirements.txt`, so my guess would be that so far it has been installed by an upstream dependency, which recently dropped it.
This small fix adds six to `requirements.txt`.
Thanks so much for your work on pywebpush! :blush:
=> Fix missing six requirement

pywebpush/__init__.py
I need to inject my own request library, and also need vapid support which only seems available in the `webpush` function and not in `WebPusher.send/encode`, so it would be great to add the `requests_session` parameter to that function too.
=> Support requests_session param in webpush fn too

pywebpush/__init__.py
`Vapid01` is not a subclass of `Vapid` (`Vapid02`). This change allows passing of an initialized `Vapid01` key object. Refs issue #137.
=> fix accepting all Vapid key instances (#137)

pywebpush/__init__.py
This is a follow up to [this PR](https://github.com/web-push-libs/pywebpush/pull/168). I wanted to create separate PR for these changes as perhaps I'm not aware if something wasn't a design decision (however I have an impression that it was simply a mistake, not a design decision 😄 )
I've updated `WebPushException.__str__` method to check if `self.response` attribute is not `None` (thus is an instance of `requests.Response`) in case of adding extra `self.response` to the string representation of `WebPushException` instance.
Currently the check was relying on checking thruthiness of `self.response` attribute. Unfortunately, this won't work properly if `requests.Response` instance has status code between 400 and 599, for which `requests.Response.__bool__` method returns `False` which in …
=> fix: check if response attribute of WebPushException object is not None in __str__ method

pyproject.toml
Use licence classifiers as described in [python packaging guide](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license):
> If you are using a standard, well-known license, it is not necessary to use this field. Instead, you should use one of the classifiers starting with `License ::`. (As a general rule, it is a good idea to use a standard, well-known license, both to avoid confusion and because some organizations avoid software whose license is unapproved.)
In the [classifiers list](https://pypi.org/classifiers/) on PyPI it is listed:
> License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)
Closes #167
=> Use Licence classifiers in pyproject.toml
