web-push-libs/pywebpush

- pywebpush/__init__.py
- pywebpush/tests/test_webpush.py
Add test cases for GCM support
closes #4
> feat: Add tests for GCM compatibility

- .coveragerc
- CHANGELOG.md
- README.md
- pywebpush/__init__.py
- pywebpush/tests/test_webpush.py
- setup.py
> feat: make python2/3 compatible

- pywebpush/__init__.py
> double param gcm_key in send's docstring

- pywebpush/__init__.py
- pywebpush/tests/test_webpush.py
- requirements.txt
- setup.py
Updated libraries and tests for latest depenedent library versions.
Note: can't tie in requires.io quite yet, investigating how to best do
that.
fixes: #18
> feat: Update requirements to latest version.

- requirements.txt
> Set minimum version

- pywebpush/__init__.py
> Change long to int to support Python 3

- README.rst
- convert_readme.sh
- pywebpush/__init__.py
- setup.py
> Convert README from markdown to restructured text

- circle.yml
- pywebpush/__init__.py
- pywebpush/tests/test_webpush.py
- requirements.txt
- setup.py
> feat: Allow empty payloads

- pywebpush/__init__.py
- pywebpush/tests/test_webpush.py
- requirements.txt
- setup.py
This fix addresses an incompatibility with Chrome.
> Vapid update

- requirements.txt
- setup.py
1.8.2:
Fixed a compilation bug affecting OpenSSL 1.1.0f
> use cryptography==1.8.2

- pywebpush/__init__.py
- pywebpush/tests/test_webpush.py
> Add AUD as WebPusher option (#63)

- pywebpush/__init__.py
- pywebpush/__main__.py
- pywebpush/tests/test_webpush.py
Also fix a few stray aes128gcm issues
closes #62
> bug: pass no keyid for aes128gcm formatting

- README.rst
- pywebpush/__init__.py
- requirements.txt
- setup.py
> feat: Update to cryptography 2.0.3

- pywebpush/__init__.py
- pywebpush/tests/test_webpush.py
I'd like to add option to use requests.Session object to optimize requests to same client and reuse connections. Here is pull request, if you are interested.
> Add option to use requests.session

- pywebpush/__init__.py
> added 'ttl' as argument for webpush function

- README.md
- README.rst
- pywebpush/__init__.py
- pywebpush/tests/test_webpush.py
- setup.py
> bug: return the remote server response in the WebpushException

- README.md
- README.rst
- pywebpush/__init__.py
- pywebpush/tests/test_webpush.py
- setup.py
> feat: Move to RFC 8188 "aes128gcm" content encoding default

- requirements.txt
- setup.py
> chore: Update requirements

- CHANGELOG.md
- pywebpush/__init__.py
- pywebpush/__main__.py
- pywebpush/tests/test_webpush.py
- setup.py
> feat: Add `--verbose` flag

- README.md
> Mention mutable `vapid_claims` in README

- CHANGELOG.md
- README.md
- README.rst
- pywebpush/__init__.py
- pywebpush/__main__.py
- pywebpush/tests/test_webpush.py
- setup.py
Now that this is one of the Critical Projects (thanks?) I should
update it to be more modern, clean up some of the crap, and
run it through flake8 at least.
> chore: Jul 2022 update
